# Generated by Django 5.0 on 2024-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_alter_pypiprocessedlink_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypiprocessedlink',
            name='github_link',
            field=models.CharField(blank=True, help_text='github_link', max_length=512, null=True, verbose_name='github_link'),
        ),
        migrations.AlterField(
            model_name='pypiprocessedlink',
            name='homepage_link',
            field=models.CharField(blank=True, help_text='homepage_link', max_length=512, null=True, verbose_name='homepage_link'),
        ),
        migrations.AlterField(
            model_name='pypisimpleindexlinks',
            name='href',
            field=models.CharField(help_text='href', max_length=512, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='pypisimpleindexlinks',
            name='processed_message',
            field=models.CharField(blank=True, help_text='processed_message', max_length=512, verbose_name='processed_message'),
        ),
        migrations.AlterField(
            model_name='pypisimpleindexlinks',
            name='pypi_project_url',
            field=models.CharField(blank=True, help_text='pypi_project_url', max_length=512, verbose_name='pypi_project_url'),
        ),
    ]
