# Generated by Django 5.0 on 2024-04-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_pypiflapyindexlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALIndexLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('url', models.CharField(help_text='url', max_length=512, verbose_name='url')),
                ('name', models.CharField(blank=True, help_text='name', max_length=512, verbose_name='name')),
                ('processed_by_flapy_message', models.CharField(blank=True, help_text='processed_message', max_length=512, null=True, verbose_name='processed_message')),
                ('processed_by_flapy', models.BooleanField(blank=True, default=False, help_text='processed', null=True, verbose_name='processed')),
                ('flapy_link', models.ForeignKey(help_text='flapy_link', on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
