# Generated by Django 5.0 on 2024-04-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_alindexlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alindexlinks',
            name='name',
        ),
    ]
