# Generated by Django 5.0 on 2024-04-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_remove_alindexlinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alindexlinks',
            name='flapy_link',
            field=models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link'),
        ),
    ]
