# Generated by Django 5.0 on 2024-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0010_alindexlinks_similar_flapy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='alindexlinks',
            name='is_a_project',
            field=models.BooleanField(blank=True, default=False, help_text='is_a_project', null=True, verbose_name='is_a_project'),
        ),
    ]
