# Generated by Django 5.0 on 2024-04-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0013_alindexlinks_can_run_flapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alindexlinks',
            name='flapy_link',
            field=models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link_analysis', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link'),
        ),
        migrations.AlterField(
            model_name='alindexlinks',
            name='similar_flapy_link',
            field=models.ForeignKey(blank=True, help_text='similar_flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_al_link_analysis', to='extractor.pypiflapyindexlinks', verbose_name='similar_flapy_link'),
        ),
        migrations.CreateModel(
            name='ALIndexLinksAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('url', models.CharField(help_text='url', max_length=512, verbose_name='url')),
                ('is_a_project', models.BooleanField(blank=True, default=False, help_text='is_a_project', null=True, verbose_name='is_a_project')),
                ('can_run_flapy', models.BooleanField(blank=True, default=False, help_text='can_run_flapy', null=True, verbose_name='can_run_flapy')),
                ('processed_by_flapy_message', models.CharField(blank=True, help_text='processed_message', max_length=512, null=True, verbose_name='processed_message')),
                ('short_description', models.CharField(blank=True, help_text='short_description', max_length=512, null=True, verbose_name='short_description')),
                ('processed_by_flapy', models.BooleanField(blank=True, default=False, help_text='processed', null=True, verbose_name='processed')),
                ('flapy_link', models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link')),
                ('similar_flapy_link', models.ForeignKey(blank=True, help_text='similar_flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_al_link', to='extractor.pypiflapyindexlinks', verbose_name='similar_flapy_link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
