# Generated by Django 5.0 on 2024-04-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0014_alter_alindexlinks_flapy_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alindexlinks',
            name='flapy_link',
            field=models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link'),
        ),
        migrations.AlterField(
            model_name='alindexlinks',
            name='similar_flapy_link',
            field=models.ForeignKey(blank=True, help_text='similar_flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_al_link', to='extractor.pypiflapyindexlinks', verbose_name='similar_flapy_link'),
        ),
        migrations.AlterField(
            model_name='alindexlinksanalysis',
            name='flapy_link',
            field=models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link_analysis', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link'),
        ),
        migrations.AlterField(
            model_name='alindexlinksanalysis',
            name='similar_flapy_link',
            field=models.ForeignKey(blank=True, help_text='similar_flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_al_link_analysis', to='extractor.pypiflapyindexlinks', verbose_name='similar_flapy_link'),
        ),
    ]
